## Candy Rankings Data (Full) {.unnumbered}


### Description

Data on 85 candy types with ingredient indicators, sugar/price
percentiles, and win percentages from 269,000 matchups.



### Usage

<pre><code class='language-R'>candy
</code></pre>


### Format

A data frame with 85 rows and 13 variables:


<dl>
<dt>competitorname</dt><dd>The name of the candy
</dd>
<dt>chocolate</dt><dd>Contains chocolate? (0=No, 1=Yes)
</dd>
<dt>fruity</dt><dd>Fruit flavored? (0=No, 1=Yes)
</dd>
<dt>caramel</dt><dd>Contains caramel? (0=No, 1=Yes)
</dd>
<dt>peanutyalmondy</dt><dd>Contains peanuts/almonds? (0=No, 1=Yes)
</dd>
<dt>nougat</dt><dd>Contains nougat? (0=No, 1=Yes)
</dd>
<dt>crispedricewafer</dt><dd>Contains crisped rice/wafers? (0=No, 1=Yes)
</dd>
<dt>hard</dt><dd>Hard candy? (0=No, 1=Yes)
</dd>
<dt>bar</dt><dd>Candy bar? (0=No, 1=Yes)
</dd>
<dt>pluribus</dt><dd>One of many in bag/box? (0=No, 1=Yes)
</dd>
<dt>sugarpercent</dt><dd>Sugar percentile within dataset
</dd>
<dt>pricepercent</dt><dd>Unit price percentile
</dd>
<dt>winpercent</dt><dd>Win percentage from 269,000 matchups
</dd>
</dl>



### Source

FiveThirtyEight candy power rankings


